### PR TITLE
Image segmentation using KMeans

### LINKED ISSUE #37: Create a python module to detect the spots on plant leaves (Use Kmeans algo)
Create a python module to detect the spots on plant leaves. Use image segmentation techniques.
Use Kmeans algorithm

### PR DESCRIPTION
**Pull request by prakhar154**
This resolves issues in #45.

### CODE REVIEW

**Comment by prakhar154** [comment]
@gshanbhag525 please review this.

**Comment by prakhar154** [comment]
@gshanbhag525 do i need to change something in this PR?

**Comment by gshanbhag525** [comment]
> @gshanbhag525 do i need to change something in this PR?

yes...can you convert this into a jupyter notebook and import the plant leaf and display the result of segmented leaf by using matplotlib .?

**Comment by gshanbhag525** [comment]
@prakhar154 For your reference you can take a look at this commit https://github.com/CropAi/Data-Modeling/blob/356bab4e8b0575aada0b249a85adf63d03263893/Spot%20Detection.ipynb

**Comment by prakhar154** [comment]
> @prakhar154 For your reference you can take a look at this commit https://github.com/CropAi/Data-Modeling/blob/356bab4e8b0575aada0b249a85adf63d03263893/Spot%20Detection.ipynb

thanks, i'll do it.

**Comment by gshanbhag525** [comment]
@prakhar154 How much time u ll need fo this?

**Comment by prakhar154** [comment]
> @prakhar154 How much time u ll need fo this?

i'll make a PR today.

**Pull request closed without merging**
