### PR TITLE
Image segmentation using Kmeans

### LINKED ISSUE #37: Create a python module to detect the spots on plant leaves (Use Kmeans algo)
Create a python module to detect the spots on plant leaves. Use image segmentation techniques.
Use Kmeans algorithm

### LINKED ISSUE #59: Get rid of .ipynb_checkpoints
Get rid of .ipynb_checkpoints by adding the hidden directory to gitignore file.

### PR DESCRIPTION
**Pull request by prakhar154**
This resolves #37.

### CODE REVIEW

**Comment by gshanbhag525** [comment]
@prakhar154 comment on https://github.com/CropAi/Data-Modeling/issues/59

**Comment by gshanbhag525** [comment]
@prakhar154 Your pr seems to solve that issue too

**Comment by prakhar154** [comment]
> @prakhar154 Your pr seems to solve that issue too

done.

**Comment by gshanbhag525** [comment]
@prakhar154 Can u close the old PR for the same issue https://github.com/CropAi/Data-Modeling/pull/46

**Comment by prakhar154** [comment]
> @prakhar154 Can u close the old PR for the same issue #46

sure.

**Comment by prakhar154** [comment]
@gshanbhag525 what changes do i need to make?

**Review by gshanbhag525 — APPROVED** [review]
good

**Comment by gshanbhag525** [comment]
@prakhar154  No , I was jus thinking if you could add a widget to select the image in jupyter notebook

**Comment by gshanbhag525** [comment]
@prakhar154 Let me know if you can do that?

**Comment by prakhar154** [comment]
> @prakhar154 Let me know if you can do that?

yes, i can do that. will you create a new issue for that?

**Pull request merged**
