### PR TITLE
predict test image

### LINKED ISSUE #41: Predict the new test images
Use the keras model created to predict the new test images and the disease class it follows.
Display the image too using matplotlib library.

### PR DESCRIPTION
**Pull request by TheTrailblazer09**
This PR solves #41 .
The model is predicting class #6 for all images. Even after changing the number of epochs and other factors the model predicts class 6 for all images. Kindly review

### CODE REVIEW

**Comment by gshanbhag525** [comment]
@TheTrailblazer09 Hi nice work. Small suggestion though ....if you give a link to your collab notebook in your PR itself....then its very easy for us to review the PR. for reference look at this notebook first cell. https://github.com/CropAi/Data-Modeling/blob/master/Crop_AI_Keras.ipynb

**Review by gshanbhag525 — COMMENTED** [review]
good

**Comment by gshanbhag525** [comment]
@TheTrailblazer09 Which model was giving wrong result...?

**Comment by gshanbhag525** [comment]
@TheTrailblazer09 You have included 2 files in your PR.... Remove the not needed file.

**Comment by TheTrailblazer09** [comment]
The Resnet model (Model_new) trained earlier always predicts class 6, irrespective of the image taken.

**Pull request merged**
