### PR TITLE
Unet model

### LINKED ISSUE #76: Image segmeantation using UNet Model
use image segmentation techniques to create a google collab notebook which consists of UNet model .

### PR DESCRIPTION
**Pull request by SubhradeepSS**
Issue handled: #76

### CODE REVIEW

**Comment by SubhradeepSS** [comment]
@gshanbhag525 I have implemented an Unet Model for the dataset.Kindly review and let me know of any changes required?

**Comment by SubhradeepSS** [comment]
@gshanbhag525 Please review my PR in reference to issue #76

**Comment by SubhradeepSS** [comment]
@gshanbhag525 Its been almost a week.Please review my PR for #76

**Review by gshanbhag525 — COMMENTED** [review]
good

**Pull request merged**
