### PR TITLE
Actions to Greet

### LINKED ISSUE #58: Github Action for greeting
I'd like to add some intermediate level github actions  to this project.

### PR DESCRIPTION
**Pull request by HarshMehta2468**
This action will greet the participant whenever a PR  is raised or an issue is created.
Closes #58

### CODE REVIEW

**Comment by gshanbhag525** [comment]
@mySTRiouscoder I want to test this before merging...

**Comment by HarshMehta2468** [comment]
> @mySTRiouscoder I want to test this before merging...
Ya sure.

**Comment by HarshMehta2468** [comment]
@gshanbhag525  This is how it works on my forked repo:

image

**Review by gshanbhag525 — COMMENTED** [review]
nicce

**Pull request merged**
