### PR TITLE
Reading Image #1

### PR DESCRIPTION
**Pull request by voldemortuk**

### CODE REVIEW

**Comment by gshanbhag525** [comment]
Hi, you are taking the absolute path in your code. Instead can you create a class and take the relative path (current directory) in the code.  Try to create in this form.
`
class DataLoader():

     def __int__(self):

     def loadData(self, folderPath):

     def saveDataToh5(self, dataPath):

`

**Comment by voldemortuk** [comment]
@gshanbhag525 will do so

**Comment by GowthamChowta** [comment]
Hi,

I think you have to return a single hd5 file of the whole data.

**Comment by voldemortuk** [comment]
@gshanbhag525 could you have a look at the latest commit I did ?

**Comment by gshanbhag525** [comment]
@Valdermaut Can u refine the commit and only include the setup.py and cropai.py.

**Comment by gshanbhag525** [comment]
@Valdermaut Also create a directory called modules and put both of the above files in that directory. Since we are tidying up the repo.

**Comment by gshanbhag525** [comment]
@Valdermaut Can u resolve the commit and push the pr to devt branch instead of master

**Comment by voldemortuk** [comment]
@gshanbhag525 I created a new pull request using the dev branch do review it

**Pull request closed without merging**
