### PR TITLE
plot

### PR DESCRIPTION
**Pull request by xAdvitya**

### CODE REVIEW

**Review by gshanbhag525 — COMMENTED** [review]
Would u be able to include this metod in the Cropai_keras jupyter notebook and show the visualization of the model building.?

**Comment by xAdvitya** [comment]
> Would u be able to include this metod in the Cropai_keras jupyter notebook and show the visualization of the model building.?

i need to create py file for that

**Comment by gshanbhag525** [comment]
@Advitya-sharma No. 
In the repository itself, there is a jupyter notebook https://github.com/CropAi/Data-Modeling/blob/master/Crop_AI_Keras.ipynb . 
It contains our model.
Create a copy of that jupyter notebook and show the visualization for that model in that notbook itself.
That what the issue was all about.

**Comment by xAdvitya** [comment]
> @Advitya-sharma No.
> In the repository itself, there is a jupyter notebook https://github.com/CropAi/Data-Modeling/blob/master/Crop_AI_Keras.ipynb .
> It contains our model.
> Create a copy of that jupyter notebook and show the visualization for that model in that notbook itself.
> That what the issue was all about.

okok

**Comment by gshanbhag525** [comment]
> @Advitya-sharma No.
> In the repository itself, there is a jupyter notebook https://github.com/CropAi/Data-Modeling/blob/master/Crop_AI_Keras.ipynb .
> It contains our model.
> Create a copy of that jupyter notebook and show the visualization for that model in that notbook itself.
> That what the issue was all about.

@Advitya-sharma Arey I had told to create a duplicate of the Crop_AI_Keras.ipynb notebook and put your plot in that. But you added in the original file itself. 

Also There is a new brach created called "devt".
I want you to amke the changes and add push ur commit to devt branch.

**Pull request closed without merging**
