### PR TITLE
#3 Requirements Text file

### PR DESCRIPTION
**Pull request by shubhamgoel90**

### CODE REVIEW

**Review by vaibagga — CHANGES_REQUESTED** [review]
List the required packages only (pip install not required)

**Comment by shubhamgoel90** [comment]
I have updated the Requirements.txt file. So, kindly review it.

**Comment by Mansi145** [comment]
Can I work on this? I can freeze the requirements in the virtual environment.

**Review by gshanbhag525 — COMMENTED** [review]
nice

**Pull request merged**
