### PR TITLE
Cross validation #2

### LINKED ISSUE #2: Cross Validation
Create a standardized python module for loading and splitting the dataset loaded from h5 file into train and validation splits (do not forget to set seed).

### PR DESCRIPTION
**Pull request by voldemortuk**
I created a standardized python module for loading and splitting the dataset loaded from h5 file into train and validation splits (do not forget to set seed).

### CODE REVIEW

**Comment by vaibagga** [comment]
Use preloaded dataset (already implemented in the master branch) and split preferably using scikit-learn's split function

**Comment by voldemortuk** [comment]
@vaibagga will do so

**Comment by gshanbhag525** [comment]
@Valdermaut Any updates on this?

**Comment by voldemortuk** [comment]
@gshanbhag525 I guess Reading Image #1 #7 #81 is done do have a look and so I will update this asap.(not more than a 1-2 day)

**Comment by voldemortuk** [comment]
@gshanbhag525 I have done the cross validation using modules but I am unable use preloaded dataset.

**Review by gshanbhag525 — COMMENTED** [review]
ok np nice

**Pull request merged**
